name: Clean Up

env:
  RESOURCE_GROUP: 'RG'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Checing Out Code
      uses: actions/checkout@v2
    - name: Remove all resources
      run: az group delete --name ${{ env.RESOURCE_GROUP }}
