name: Deploy Function App

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: modeldeployxd
  CONTAINER_REGISTRY: 'modelcontainerxd.azurecr.io'
  IMAGE_NAME: 'modelimage'
  RESOURCE_GROUP: 'RG'
  TAG: '55e7a8de4c31d0e04922d482c96f2ff00f482d9c'
  STORAGE_ACCOUNT: 'rgml8425'
  PLAN: 'ASP-rgml-a1ce'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy Function App
      run: |
        az functionapp update --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --runtime custom --image ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} 
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
